const { test, expect } = require('@playwright/test');

test.beforeEach(async ({page})=>{await page.goto('/index.html');const gate=page.locator('#ageYes');if(await gate.count())await gate.click();});

test('discovery, filters and profile navigation work',async({page})=>{await expect(page.getByRole('heading',{name:/Entdecke passende Profile/i})).toBeVisible();await expect(page.locator('#listingGrid .card').first()).toBeVisible();await page.selectOption('#city','Köln');await expect(page.locator('#listingGrid .card').first()).toBeVisible();const count=await page.locator('#listingGrid .card').count();expect(count).toBeGreaterThan(0);await page.locator('#listingGrid .card').first().click();await expect(page.locator('#profileRoot h1')).toBeVisible();await expect(page.getByRole('button',{name:/Anfrage senden/i}).first()).toBeVisible();});

test('polished local showcase profile stays stable and complete',async({page})=>{await page.goto('/profile.html?id=sophia-koeln');const gate=page.locator('#ageYes');if(await gate.count())await gate.click();await expect(page.getByRole('heading',{name:'Sophia'})).toBeVisible();await expect(page.locator('.profile-summary-card')).toBeVisible();await expect(page.locator('#profileGallery .profile-thumb')).toHaveCount(4);await expect(page.getByRole('heading',{name:'Auf einen Blick'})).toBeVisible();await expect(page.getByRole('heading',{name:'Klare Zeitmodelle'})).toBeVisible();await expect(page.locator('.offer-row')).toHaveCount(3);await expect(page.locator('#availabilityBox .day-card')).toHaveCount(7);await expect(page.locator('#reviewsBox .demo-review').first()).toBeVisible();await expect(page.locator('#similarGrid .card').first()).toBeVisible();});

test('standalone trust feature stays removed from visitor flow',async({page})=>{await expect(page.locator('#vertrauen')).toHaveCount(0);await expect(page.getByRole('link',{name:'Vertrauen'})).toHaveCount(0);await expect(page.locator('#listingGrid .card').first()).toBeVisible();await page.locator('#listingGrid .card').first().click();await expect(page.locator('#trustBox')).toHaveCount(0);await expect(page.getByRole('heading',{name:/Was wurde geprüft/i})).toHaveCount(0);});

test('WhatsApp action is visible on profiles and opens WhatsApp',async({page})=>{await expect(page.locator('#listingGrid .card').first()).toBeVisible();await page.locator('#listingGrid .card').first().click();const button=page.locator('#whatsappBtn');await expect(button).toBeVisible();await expect(button).toHaveAttribute('href',/^https:\/\/wa\.me\//);});

test('unknown profile never falls back to a different listing',async({page})=>{await page.goto('/profile.html?id=00000000-0000-4000-8000-000000000001');await expect(page.getByRole('heading',{name:'Dieses Profil ist nicht verfügbar.'})).toBeVisible();await expect(page.locator('#profileRoot .profile-shell')).toHaveCount(0);});

test('demo inquiry opens privacy-aware form',async({page})=>{await page.goto('/profile.html?id=sophia-koeln');await page.getByRole('button',{name:/Anfrage senden/i}).first().click();await expect(page.locator('#inquiryForm')).toBeVisible();await expect(page.locator('#inquiryForm input[name="privacy"]')).toBeVisible();await expect(page.locator('#inquiryForm textarea[name="message"]')).toBeVisible();});

test('invalid private conversation token is rejected',async({page})=>{await page.goto('/conversation.html?token=invalid-token');await expect(page.locator('#threadStatus')).toHaveText('Ungültiger Link');await expect(page.locator('#threadMessages')).toContainText('ungültig');});

test('provider registration UI exposes mandatory consents',async({page})=>{await page.goto('/login.html');await page.getByRole('button',{name:/Noch kein Konto/i}).click();await expect(page.getByRole('heading',{name:/registrieren/i})).toBeVisible();await expect(page.locator('#displayName')).toBeVisible();await expect(page.locator('#phone')).toBeVisible();await expect(page.locator('#privacyAccept')).toBeVisible();await expect(page.locator('#adultAccept')).toBeVisible();await expect(page.locator('#rulesAccept')).toBeVisible();});

test('customer registration exposes separate 18+ privacy and terms consent',async({page})=>{await page.goto('/customer.html');await page.getByRole('button',{name:/Noch kein Konto/i}).click();await expect(page.locator('#customerAdult')).toBeVisible();await expect(page.locator('#customerPrivacy')).toBeVisible();await expect(page.locator('#customerTerms')).toBeVisible();});

test('reporting includes moderation appeal',async({page})=>{await page.goto('/meldestelle.html');await expect(page.getByRole('heading',{name:/Meldestelle/i})).toBeVisible();await page.selectOption('#reportReason',{label:'Beschwerde gegen Moderationsentscheidung'});await expect(page.locator('#reportReason')).toHaveValue('Beschwerde gegen Moderationsentscheidung');});
